### ISSUE TITLE
Format being ignored...

### ISSUE THREAD

**Issue by martyn62** [wdelfuego/nova-datetime#4]
Trying to set the format using globalFormat (and have tried inline as well). Ripping my hair out!

Getting an error as below..
![Screenshot 2022-10-28 212715](https://user-images.githubusercontent.com/1910658/198726941-26bf3abd-dfc6-4062-9930-f5b9757f5e47.jpg)

Seems like globalFormat & have tried inline withDateFormat are being ignored.
![Screenshot 2022-10-28 213054](https://user-images.githubusercontent.com/1910658/198726963-dd77c6ef-ad28-4e0b-9887-fe5b4c884cd8.jpg)

Any ideas?

Nova  4.17.1

Everything up to date.

**Comment by martyn62** [comment]
Just to confirm the config is in place.
![image](https://user-images.githubusercontent.com/1910658/198730274-60f203b8-93f9-40bc-98e3-7aae0a0fe031.png)

**Comment by wdelfuego** [comment]
Hi @martyn62 !

I don't think this is an issue with this package; you're getting an SQL error but this package isn't involved with how `DateTime` objects are stored; only with how they're displayed in Nova fields. 

If you remove this package from your project, do you still get these errors using the default Nova `DateTime` fields?

**Comment by martyn62** [comment]
Thanks for your reply. Yes my mistake sorry I'd overlooked protected $casts on the items.

**Comment by wdelfuego** [comment]
Good to hear, thanks for the update!
